apiVersion: apps/v1
kind: Deployment
metadata:
  name: magikarp-deployment
  labels:
    app: magikarp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magikarp
  template:
    metadata:
      labels:
        app: magikarp
    spec:
      containers:
        - name: magikarp
          image: gcr.io/magikarp-295201/magikarp-server:latest
          ports:
            - containerPort: 7000
          env:
            - name: MAGIKARP_JSON
              valueFrom:
                secretKeyRef:
                  name: magikarp-secret
                  key: magikarp-295201-16cb5b55b6fb.json
---
apiVersion: v1
kind: Service
metadata:
  name: magikarp-service
spec:
  selector:
    app: magikarp
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: LoadBalancer
  loadBalancerIP: 35.190.179.162
